language: go
go:
 - release
 - tip

before_install:
 - export PATH=/home/travis/gopath/bin:$PATH

install:
 - go get github.com/axw/gocov/gocov
 - go get github.com/smartystreets/goconvey/convey
 - go get golang.org/x/tools/cmd/cover
 - go get github.com/mattn/goveralls
 - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi

script:
 - $HOME/gopath/bin/goveralls -service=travis-ci
