language: go
go:
 - release
 - tip

before_install:
 - export PATH=/home/travis/gopath/bin:$PATH

install:
 - mkdir -p $HOME/gopath/src/cydev.ru/hath
 - rsync -az ${TRAVIS_BUILD_DIR}/ $HOME/gopath/src/cydev.ru/hath/
 - export TRAVIS_BUILD_DIR=$HOME/gopath/src/cydev.ru/hath
 - cd $TRAVIS_BUILD_DIR
 - go get .
 - go get github.com/smartystreets/goconvey/convey
 - go get golang.org/x/tools/cmd/cover
 - go get github.com/mattn/goveralls
 - go install github.com/mattn/goveralls

script:
 - go test -covermode=count -coverprofile=profile.cov
 - goveralls -coverprofile=profile.cov -service=travis-ci
