language: go
go:
 - auto
 - tip

before_install:
 - mkdir -p $HOME/gopath/src/cydev.ru/
 - mv $HOME/gopath/src/github.com/cydev/hath $HOME/gopath/src/cydev.ru/hath
 - cd $HOME/gopath/src/cydev.ru/hath

install:
 - go get -t .
 - go get github.com/axw/gocov/gocov
 - go get github.com/smartystreets/goconvey/convey
 - go get golang.org/x/tools/cmd/cover
 - go get github.com/mattn/goveralls

script:
 - $HOME/gopath/bin/goveralls -service=travis-ci
