version: "{build}"

os: Windows Server 2012 R2

clone_folder: c:\gopath\src\github.com\cydev\hath

environment:
  GOPATH: c:\gopath

install:
install:
  - set PATH=%LOCALAPPDATA%\atom\bin;%GOPATH%\bin;c:\go\bin;%PATH%
  - appveyor DownloadFile https://storage.googleapis.com/golang/go1.4.2.windows-amd64.msi
  - msiexec /i go1.4.2.windows-amd64.msi /q
  - go version
  - go env
  - mkdir c:\gopath
  - go version
  - go env
  - go get -v -t .

build_script:
  - go test -v .
