version: "{build}"

os: Windows Server 2012 R2

clone_folder: c:\gopath\src\cydev.ru\hath

environment:
  GOPATH: c:\gopath

install:
  - go version
  - go get -v -t .

build_script:
  - go test -v .
